### ISSUE TITLE
Internal Torque

### ISSUE THREAD

**Issue by jamesmcgill** [gamephysicsweekend/VulkanRenderer#1]
Thanks for the great book!
I've completed the first one but I couldn't really grasp this part 100%.
I was wondering if you could point to any resources where I could see, in particularly, where 'r = w x I.w' comes from?

Probably it's derived from the other equations in the book but I couldn't figure it out. 

https://github.com/gamephysicsweekend/VulkanRenderer/blob/33e27fa96e63c4d9e5525c71425b0b2a2fabfc94/completed/Book00/Physics/Body.cpp#L157

**Comment by gamephysicsweekend** [comment]
Congratulations on completing the first book.  I'm glad you found it useful.

I didn't bother to derive the internal torque from first principles.  But there's definitely plenty of resources out there for trying to wrap your head around it.  Here's a few to get started:

https://en.wikipedia.org/wiki/Tennis_racket_theorem

https://www.youtube.com/watch?v=1VPfZ_XzisU

https://www.youtube.com/watch?v=6CztfTbPtoo&list=PLUHTGp7T4Zn_FU64InC0C8ZsejaxMtO3s&index=28

The first two links are good high level introductions.  But the last link is to a classical mechanics lecture from NTNU that contains a rigorous derivation.

I hope that helps!

**Comment by jamesmcgill** [comment]
Perfect, thanks I'll take a look at those.
