### ISSUE TITLE
Game Physics In One Weekend code issue for calculating ray trace

### ISSUE THREAD

**Issue by zeafynx** [gamephysicsweekend/VulkanRenderer#4]
In page 56, I think the code for solving quadratic equation in function RaySphere is wrong.
```
const float delta = b * b - a * c;
```
However, I think the correct one should be:
```
const float delta = b * b - 4 * a *c;
```

**Comment by gamephysicsweekend** [comment]
Suprisingly, the four factors out of the equation.  https://en.wikipedia.org/wiki/Line%E2%80%93sphere_intersection

Cheers!
